#map_type: voxel
#map_type: costmap
robot_radius: 0.25

footprint: [[0.23,0.18],[0.25,0],[0.23,-0.18],[-0.23, -0.18],[-0.23,0.18]]
recovery_behavior_enabled: true

# controller_frequency: 5
controller_frequency: 20

obstacle_layer:
  enabled:              true
  combination_method:   1
  track_unknown_space:  false
  origin_z: 0.0
  z_voxels: 20
  z_resolution: 0.1
  unknown_cost_value: 0
  unknown_threshold: 8
  mark_threshold: 0
  publish_voxel_map: false

  obstacle_range: 15.80
  raytrace_range: 16.0
  #footprint: [[-0.3,-0.4],[-0.3,1.03],[-0.0,1.03],[0.3, 1.03],[0.3,-0.4]]
  robot_radius: 0.25
  inflation_radius: 0.05
  #inf_is_valid: true
  max_obstacle_height: 1
  min_obstacle_height: -1
  controller_frequency: 20
  observation_sources: scan 
  #point_cloud_sensor

  scan: {sensor_frame: base_link,  observation_persistence: 0.0, 
  max_obstacle_height: 0.8, min_obstacle_height: -0.8, data_type: LaserScan, topic: /scan, 
  marking: true,clearing: true}

inflation_layer:
 enabled:              true
 cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius:     0.1  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
 enabled: true

