# TrajectoryPlannerROS:

#   meter_scoring: true
#   holonomic_robot: false

#   max_vel_x: 0.6
#   min_vel_x: 0.1

#   max_vel_y: 0
#   min_vel_y: 0

#   max_vel_theta: 1.2
#   min_vel_theta: -1.2

#   min_in_place_vel_theta: 0.5
#   escape_vel: -0.5

#   acc_lim_theta: 1
#   acc_lim_x: 0.1
#   acc_lim_y: 0
# xy_goal_tolerance: 0.15
# yaw_goal_tolerance: 0.15
TebLocalPlannerROS:

  odom_topic: /odom
  map_frame: /map
  
  via_points: /move_base/GlobalPlanner/plan 

  # Trajecto

  teb_autosize: True
  dt_ref: 0.20 #期望的轨迹时间分辨率
  dt_hysteresis: 0.015 #根据当前时间分辨率自动调整大小的滞后现象，通常约为。建议使用dt ref的10%
  
  #global_plan_overwrite_orientation: True #覆盖由全局规划器提供的局部子目标的方向
  max_global_plan_lookahead_dist: 2.0 #指定考虑优化的全局计划子集的最大长度
  feasibility_check_no_poses: 4 #每个采样间隔的姿态可行性分析数，default：4
  global_plan_overwrite_orientation: True     
  #publish_feedback: True 

  allow_init_with_backwards_motion: True
  global_plan_viapoint_sep: -1
  global_plan_prune_distance: 1
  exact_arc_length: False
  publish_feedback: True


  # Robot
  max_vel_x: 1.2
  max_vel_x_backwards: 0.35
  max_vel_theta: 0.9
  acc_lim_x: 1.500
  acc_lim_theta: 2.0

  #仅适用于全向轮
  # max_vel_y (double, default: 0.0)  
  # acc_lim_y (double, default: 0.5)

  # ********************** Carlike robot parameters ********************
  min_turning_radius: 0.85      # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase: 0.31              # Wheelbase of our robot
  cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
  # ********************************************************************

  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "line"
    # radius: 0.2 # for type "circular"
    line_start: [-0.19, 0.0] # for type "line"
    line_end: [0.19, 0.0] # for type "line"
    # front_offset: 0.2 # for type "two_circles"
    # front_radius: 0.2 # for type "two_circles"
    # rear_offset: 0.2 # for type "two_circles"
    # rear_radius: 0.2 # for type "two_circles"
    # vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

  # GoalTolerance
      
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.3
  free_goal_vel: True
  # complete_global_plan: True   
  # Obstacles
    
  min_obstacle_dist: 0.29 # 与障碍的最小期望距离,注意，teb_local_planner本身不考虑膨胀半径
  include_costmap_obstacles: True #应否考虑到局部costmap的障碍
  costmap_obstacles_behind_robot_dist: 4.5 #考虑后面n米内的障碍物
  obstacle_poses_affected: 30 #为了保持距离，每个障碍物位置都与轨道上最近的位置相连。
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "" # deactivate plugin
  #costmap_converter_spin_thread: True
  #costmap_converter_rate: 5
  #costmap_converter/CostmapToPolygonsDBSMCCH:
  #  cluster_max_distance: 0.4
  #  cluster_min_pts: 0.01
  #  cluster_max_pts: 20
  #  convex_hull_min_pt_separation: 0.1 



  # Optimization
      
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.14 #0.14
  weight_inflation: 1000
  weight_max_vel_x: 300 #300
  weight_max_vel_theta: 1
  weight_acc_lim_x: 350
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 300
  weight_obstacle: 1000
  weight_dynamic_obstacle: 1000 # not in use yet
  # alternative_time_cost: False # not in use yet
  selection_alternative_time_cost: False
  # Homotopy Class Planner
  weight_viapoint: 0.5
  inflation_dist: 0.5
  enable_homotopy_class_planning: False
  enable_multithreading: False
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False

  # Recovery

  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 0.2
  oscillation_filter_duration: 10